//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Table()
        {
            this.id = 0;
        }
    
        public int id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string YearOfIssue { get; set; }
        public string TypeOfEngine { get; set; }
        public string PowerOfEngine { get; set; }
        public string SizeOfEngine { get; set; }
        public string Cost { get; set; }
        public string Count { get; set; }
        public string Color { get; set; }
        public string Condition { get; set; }
        public string Image { get; set; }
    }
}
